# Site settings
title: "Andrew Zhuravchak"
description: "Andrew Zhuravchak personal website and resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Andrew Zhuravchak"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "zhuravchakandrew@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-555"
resume_contact_address:         "Lviv, Ukraine"

resume_header_contact_info:     "Lviv, Ukraine • zhuravchak@ucu.edu.ua"
display_header_contact_info:    "false"

resume_header_intro: "
<ul>
<li>Software engineer with 3+ years of experience (including both commercial and non-profit projects) ranging from the web development and competitive programming to the blockchain technology</li>
<li>Developed image compression algorithm which is better than standard SVD approach in 2-3 times and built linear algebra library which is 10-15% better then Eigen(industrial standard for such computation) (you can find this projects on my GitHub account)</li>
<li>Keen on data analysis and machine learning. Linux admirer</li>
</ul>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
#resume_section_skills:          true
resume_section_most_proud_of:   true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Retsediv"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:         "https://www.facebook.com/a.zhuravchak"
  resume_linkedin_url:          "https://www.linkedin.com/in/andrew-zhuravchak-9647b7a1/"
  # resume_instagram_url:         "insert your Instagram URL here"
#  resume_website_url:           "http://joelglovier.com"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
